// arihayat.com - Gerçek Ürün Kataloğu
export const ARIHAYAT_PRODUCTS = [
  // === BAL KATEGORİSİ ===
  { id: 'bal-01', name: 'Çiçek Balı 400 gr', slug: 'cicek-bali-400-gr', price: 300, originalPrice: null, category: 'bal', categoryLabel: 'Bal', image: '/images/products/bal.png', description: 'Doğanın en taze çiçeklerinden toplanan %100 saf çiçek balı. 400 gr.', stock: 50, isActive: true, isFreeShipping: false, isNew: false, isFeatured: true },
  { id: 'bal-02', name: 'Çiçek Balı 850 gr', slug: 'cicek-bali-850-gr', price: 600, originalPrice: null, category: 'bal', categoryLabel: 'Bal', image: '/images/products/bal.png', description: 'Doğanın en taze çiçeklerinden toplanan %100 saf çiçek balı. 850 gr.', stock: 40, isActive: true, isFreeShipping: false, isNew: false, isFeatured: true },
  { id: 'bal-03', name: 'Çiçek Balı 5 kg', slug: 'cicek-bali-5-kg', price: 3500, originalPrice: null, category: 'bal', categoryLabel: 'Bal', image: '/images/products/bal.png', description: 'Ailecek kullanım için ekonomik boy. %100 doğal çiçek balı. 5 kg.', stock: 20, isActive: true, isFreeShipping: true, isNew: false, isFeatured: false },
  { id: 'bal-04', name: 'Çam Balı 400 gr', slug: 'cam-bali-400-gr', price: 350, originalPrice: null, category: 'bal', categoryLabel: 'Bal', image: '/images/products/bal.png', description: 'Ege ormanlarının kıymetli çam balı. Koyu rengi ve kendine has aromasıyla. 400 gr.', stock: 35, isActive: true, isFreeShipping: false, isNew: false, isFeatured: false },
  { id: 'bal-05', name: 'Çam Balı 850 gr', slug: 'cam-bali-850-gr', price: 700, originalPrice: null, category: 'bal', categoryLabel: 'Bal', image: '/images/products/bal.png', description: 'Ege ormanlarının kıymetli çam balı. Koyu rengi ve kendine has aromasıyla. 850 gr.', stock: 30, isActive: true, isFreeShipping: false, isNew: false, isFeatured: false },
  { id: 'bal-06', name: 'Kestane Ihlamur Balı 400 gr', slug: 'kestane-ihlamur-bali-400-gr', price: 740, originalPrice: null, category: 'bal', categoryLabel: 'Bal', image: '/images/products/bal.png', description: 'Kestane ve ihlamur çiçeklerinin eşsiz harmanı. Güçlü antioksidan içeriği. 400 gr.', stock: 25, isActive: true, isFreeShipping: false, isNew: false, isFeatured: true },
  { id: 'bal-07', name: 'Kestane Ihlamur Balı 850 gr', slug: 'kestane-ihlamur-bali-850-gr', price: 1480, originalPrice: null, category: 'bal', categoryLabel: 'Bal', image: '/images/products/bal.png', description: 'Kestane ve ihlamur çiçeklerinin eşsiz harmanı. Güçlü antioksidan içeriği. 850 gr.', stock: 20, isActive: true, isFreeShipping: true, isNew: false, isFeatured: false },
  { id: 'bal-08', name: 'Meşe Balı 400 gr', slug: 'mese-bali-400-gr', price: 480, originalPrice: null, category: 'bal', categoryLabel: 'Bal', image: '/images/products/bal.png', description: 'Nadir ve değerli meşe balı. Koyu rengi ve yoğun aromasıyla özel bir tat. 400 gr.', stock: 15, isActive: true, isFreeShipping: false, isNew: false, isFeatured: false },
  { id: 'bal-09', name: 'Orman Balı 400 gr', slug: 'orman-bali-400-gr', price: 425, originalPrice: null, category: 'bal', categoryLabel: 'Bal', image: '/images/products/bal.png', description: 'Orman florası zenginliğini taşıyan çok çiçekli bal. 400 gr.', stock: 0, isActive: true, isFreeShipping: false, isNew: false, isFeatured: false },
  { id: 'bal-10', name: 'Doğal Orman Balı 850 gr', slug: 'dogal-orman-bali-850-gr', price: 850, originalPrice: null, category: 'bal', categoryLabel: 'Bal', image: '/images/products/bal.png', description: 'Üreticiden saf orman balı. Doğanın tüm şifasını içinde barındırır. 850 gr.', stock: 0, isActive: true, isFreeShipping: false, isNew: false, isFeatured: false },
  { id: 'bal-11', name: 'Arı Hayat Krem Bal 400 gr', slug: 'krem-bal-400-gr', price: 350, originalPrice: null, category: 'bal', categoryLabel: 'Bal', image: '/images/products/bal.png', description: 'Pürüzsüz kıvamı ve zengin aromasıyla doğallığın krem hali. 400 gr.', stock: 45, isActive: true, isFreeShipping: false, isNew: true, isFeatured: true },

  // === ARI SÜTÜ KATEGORİSİ ===
  { id: 'ari-01', name: 'Arı Sütü Yerli Üretim 100 gr', slug: 'ari-sutu-yerli-uretim-100-gr', price: 4000, originalPrice: null, category: 'ari-sutu', categoryLabel: 'Arı Sütü', image: '/images/products/ari-sutu.png', description: 'Kendi kovanlarımızdan taze sağım, dondurulmuş saf yerli arı sütü. 100 gr.', stock: 30, isActive: true, isFreeShipping: true, isNew: false, isFeatured: true },
  { id: 'ari-02', name: 'Arı Sütü Yerli Üretim 50 gr', slug: 'ari-sutu-yerli-uretim-50-gr', price: 2000, originalPrice: null, category: 'ari-sutu', categoryLabel: 'Arı Sütü', image: '/images/products/ari-sutu.png', description: 'Kendi kovanlarımızdan taze sağım, dondurulmuş saf yerli arı sütü. 50 gr.', stock: 40, isActive: true, isFreeShipping: true, isNew: false, isFeatured: true },
  { id: 'ari-03', name: 'Doğal Arı Sütü 40 gr | Taze & Yerli Üretim', slug: 'dogal-ari-sutu-40-gr', price: 1600, originalPrice: 1800, category: 'ari-sutu', categoryLabel: 'Arı Sütü', image: '/images/products/ari-sutu.png', description: 'Taze ve yerli üretim doğal arı sütü. Bağışıklık sistemi için güçlü destek. 40 gr.', stock: 35, isActive: true, isFreeShipping: true, isNew: false, isFeatured: false },
  { id: 'ari-04', name: 'Yerli Arı Sütü 20 gr', slug: 'yerli-ari-sutu-20-gr', price: 800, originalPrice: 900, category: 'ari-sutu', categoryLabel: 'Arı Sütü', image: '/images/products/ari-sutu.png', description: 'Başlangıç dozu için ideal. Kendi kovanlarımızdan elde edilen saf yerli arı sütü. 20 gr.', stock: 50, isActive: true, isFreeShipping: false, isNew: false, isFeatured: false },

  // === PROPOLİS KATEGORİSİ ===
  { id: 'pro-01', name: 'Zeytinyağlı Propolis 50 ml', slug: 'zeytinyagli-propolis-50-ml', price: 350, originalPrice: 400, category: 'propolis', categoryLabel: 'Propolis', image: '/images/products/propolis.png', description: 'Alkol içermeyen, soğuk sıkım zeytinyağında çözülmüş saf propolis ekstraktı. 50 ml.', stock: 60, isActive: true, isFreeShipping: false, isNew: false, isFeatured: true },
  { id: 'pro-02', name: 'Propolis 20cc Zeytinyağında Çözülmüş', slug: 'propolis-20cc-zeytinyaginda', price: 175, originalPrice: 200, category: 'propolis', categoryLabel: 'Propolis', image: '/images/products/propolis.png', description: 'Zeytinyağında çözülmüş saf propolis. Yüksek emilim ve doğal içerik. 20 cc.', stock: 70, isActive: true, isFreeShipping: false, isNew: true, isFeatured: false },

  // === KARIŞIM KATEGORİSİ ===
  { id: 'kar-01', name: 'Karışım Kids 225 gr', slug: 'karisim-kids-225-gr', price: 420, originalPrice: null, category: 'karisim', categoryLabel: 'Karışım', image: '/images/products/karisim.png', description: 'Çocuklar için özel formül. Yerli arı sütü, ham bal, polen ve propolis. 225 gr.', stock: 45, isActive: true, isFreeShipping: false, isNew: false, isFeatured: true },
  { id: 'kar-02', name: 'Karışım Kids 400 gr', slug: 'karisim-kids-400-gr', price: 650, originalPrice: 710, category: 'karisim', categoryLabel: 'Karışım', image: '/images/products/karisim.png', description: 'Çocuklar için özel formül. Yerli arı sütü, ham bal, polen ve propolis. 400 gr.', stock: 40, isActive: true, isFreeShipping: false, isNew: false, isFeatured: false },
  { id: 'kar-03', name: 'Karışım Kids 850 gr', slug: 'karisim-kids-850-gr', price: 1350, originalPrice: 1420, category: 'karisim', categoryLabel: 'Karışım', image: '/images/products/karisim.png', description: 'Çocuklar için özel formül. Yerli arı sütü, ham bal, polen ve propolis. 850 gr.', stock: 30, isActive: true, isFreeShipping: true, isNew: false, isFeatured: false },
  { id: 'kar-04', name: 'Yetişkin Karışım 225 gr', slug: 'yetiskin-karisim-225-gr', price: 710, originalPrice: null, category: 'karisim', categoryLabel: 'Karışım', image: '/images/products/karisim.png', description: 'Yetişkinler için özel formül. Yerli ham bal, arı sütü, polen ve propolis. 225 gr.', stock: 40, isActive: true, isFreeShipping: false, isNew: false, isFeatured: true },
  { id: 'kar-05', name: 'Yetişkin Karışım 400 gr', slug: 'yetiskin-karisim-400-gr', price: 1100, originalPrice: 1165, category: 'karisim', categoryLabel: 'Karışım', image: '/images/products/karisim.png', description: 'Yetişkinler için özel formül. Yerli ham bal, arı sütü, polen ve propolis. 400 gr.', stock: 35, isActive: true, isFreeShipping: false, isNew: false, isFeatured: false },
  { id: 'kar-06', name: '850 gr Yetişkin Yerli Ham Bal, Polen, Arı Sütü ve Propolis Karışımı', slug: 'yetiskin-karisim-850-gr-tam', price: 2200, originalPrice: 2330, category: 'karisim', categoryLabel: 'Karışım', image: '/images/products/karisim.png', description: 'Tam içerikli yetişkin karışımı. Yerli ham bal, arı sütü, polen ve propolis. 850 gr.', stock: 25, isActive: true, isFreeShipping: true, isNew: false, isFeatured: false },
  { id: 'kar-07', name: 'Yetişkin Karışım 850 gr + Propolis 50cc Zeytinyağında', slug: 'yetiskin-karisim-850-gr-propolis', price: 2500, originalPrice: 2700, category: 'karisim', categoryLabel: 'Karışım', image: '/images/products/karisim.png', description: 'Yetişkin karışımı + zeytinyağlı propolis hediye. Tam bağışıklık desteği paketi. 850 gr.', stock: 20, isActive: true, isFreeShipping: true, isNew: false, isFeatured: false },
  { id: 'kar-08', name: 'Yetişkin Karışım 225 gr + 2 adet Propolis 50cc', slug: 'yetiskin-karisim-225-gr-propolis-2x', price: 1310, originalPrice: 1450, category: 'karisim', categoryLabel: 'Karışım', image: '/images/products/karisim.png', description: 'Yetişkin karışımı + 2 adet zeytinyağlı propolis. Avantajlı paket.', stock: 20, isActive: true, isFreeShipping: false, isNew: true, isFeatured: false },
  { id: 'kar-09', name: 'Karışım Kids 850 gr + Propolis 50cc Zeytinyağında', slug: 'karisim-kids-850-gr-propolis', price: 1650, originalPrice: 1790, category: 'karisim', categoryLabel: 'Karışım', image: '/images/products/karisim.png', description: 'Çocuk karışımı + zeytinyağlı propolis. Çocuklar için tam koruma paketi.', stock: 25, isActive: true, isFreeShipping: true, isNew: true, isFeatured: false },

  // === BEŞLİ KARIŞIM (ARI EKMEKLİ) ===
  { id: 'bes-01', name: 'ARI EKMEKLİ 225 gr Yetişkin Karışımı', slug: 'ari-ekmekli-225-gr-yetiskin', price: 730, originalPrice: null, category: 'besli-karisim', categoryLabel: 'Beşli Karışım', image: '/images/products/karisim.png', description: 'Arı ekmeği (perga) ilaveli yetişkin karışımı. Bal, arı sütü, polen, propolis + arı ekmeği. 225 gr.', stock: 30, isActive: true, isFreeShipping: false, isNew: false, isFeatured: false },
  { id: 'bes-02', name: 'ARI EKMEKLİ 400 gr Yetişkin Karışımı', slug: 'ari-ekmekli-400-gr-yetiskin', price: 1200, originalPrice: null, category: 'besli-karisim', categoryLabel: 'Beşli Karışım', image: '/images/products/karisim.png', description: 'Arı ekmeği (perga) ilaveli yetişkin karışımı. Bal, arı sütü, polen, propolis + arı ekmeği. 400 gr.', stock: 25, isActive: true, isFreeShipping: false, isNew: false, isFeatured: true },
  { id: 'bes-03', name: 'ARI EKMEKLİ 850 gr Yetişkin Karışımı', slug: 'ari-ekmekli-850-gr-yetiskin', price: 2400, originalPrice: null, category: 'besli-karisim', categoryLabel: 'Beşli Karışım', image: '/images/products/karisim.png', description: 'Arı ekmeği (perga) ilaveli yetişkin karışımı. Bal, arı sütü, polen, propolis + arı ekmeği. 850 gr.', stock: 20, isActive: true, isFreeShipping: true, isNew: false, isFeatured: false },
  { id: 'bes-04', name: 'ARI EKMEKLİ Karışım Kids 225 gr', slug: 'ari-ekmekli-karisim-kids-225-gr', price: 440, originalPrice: null, category: 'besli-karisim', categoryLabel: 'Beşli Karışım', image: '/images/products/karisim.png', description: 'Arı ekmeği ilaveli çocuk karışımı. Doğal beş bileşen bir arada. 225 gr.', stock: 30, isActive: true, isFreeShipping: false, isNew: false, isFeatured: false },
  { id: 'bes-05', name: 'ARI EKMEKLİ Karışım Kids 400 gr', slug: 'ari-ekmekli-karisim-kids-400-gr', price: 770, originalPrice: null, category: 'besli-karisim', categoryLabel: 'Beşli Karışım', image: '/images/products/karisim.png', description: 'Arı ekmeği ilaveli çocuk karışımı. Doğal beş bileşen bir arada. 400 gr.', stock: 25, isActive: true, isFreeShipping: false, isNew: false, isFeatured: false },
  { id: 'bes-06', name: 'ARI EKMEKLİ Karışım Kids 850 gr', slug: 'ari-ekmekli-karisim-kids-850-gr', price: 1550, originalPrice: null, category: 'besli-karisim', categoryLabel: 'Beşli Karışım', image: '/images/products/karisim.png', description: 'Arı ekmeği ilaveli çocuk karışımı. Doğal beş bileşen bir arada. 850 gr.', stock: 20, isActive: true, isFreeShipping: true, isNew: false, isFeatured: false },

  // === POLEN / ARI EKMEĞİ ===
  { id: 'pol-01', name: 'Arı Ekmeği 100 gr', slug: 'ari-ekmegi-100-gr', price: 450, originalPrice: null, category: 'polen-ari-ekmegi', categoryLabel: 'Polen & Arı Ekmeği', image: '/images/products/polen.png', description: 'İşçi arıların fermente ettiği protein ve vitamin deposu arı ekmeği (perga). 100 gr.', stock: 40, isActive: true, isFreeShipping: false, isNew: false, isFeatured: true },
  { id: 'pol-02', name: 'Yerli Polen 100 gr', slug: 'yerli-polen-100-gr', price: 150, originalPrice: 175, category: 'polen-ari-ekmegi', categoryLabel: 'Polen & Arı Ekmeği', image: '/images/products/polen.png', description: 'Yerli üretim taze çiçek poleni. Renk renk granüller, doğal enerji kaynağı. 100 gr.', stock: 55, isActive: true, isFreeShipping: false, isNew: false, isFeatured: false },

  // === BİTKİSEL YAĞLAR ===
  { id: 'yag-01', name: '100 ml Kantaron Yağı', slug: 'kantaron-yagi-100-ml', price: 155, originalPrice: null, category: 'bitkisel-yaglar', categoryLabel: 'Bitkisel Yağlar', image: '/images/products/karisim.png', description: 'Geleneksel yöntemlerle hazırlanmış saf kantaron (sarı kantaron) yağı. 100 ml.', stock: 35, isActive: true, isFreeShipping: false, isNew: false, isFeatured: false },
];

export const ARIHAYAT_CATEGORIES = [
  { id: 'cat-01', slug: 'ari-sutu', name: 'Arı Sütü', description: 'Kendi kovanlarımızdan taze sağım, dondurulmuş saf yerli arı sütü ürünleri.', image: '/images/products/ari-sutu.png', productCount: 4 },
  { id: 'cat-02', slug: 'besli-karisim', name: 'Beşli Karışım', description: 'Arı ekmeği ilaveli, beş doğal bileşeni bir arada sunan özel karışımlar.', image: '/images/products/karisim.png', productCount: 6 },
  { id: 'cat-03', slug: 'karisim', name: 'Karışım', description: 'Yerli arı sütü, ham bal, Polen ve Propolis karışımı. Çocuk ve yetişkin formülleri.', image: '/images/products/karisim.png', productCount: 9 },
  { id: 'cat-04', slug: 'propolis', name: 'Propolis', description: 'Zeytinyağında çözülmüş, alkol içermeyen saf propolis ekstraktı ürünleri.', image: '/images/products/propolis.png', productCount: 4 },
  { id: 'cat-05', slug: 'polen-ari-ekmegi', name: 'Polen & Arı Ekmeği', description: 'Katkısız arı ekmeği ve yerli çiçek poleni. Protein ve vitamin deposu.', image: '/images/products/polen.png', productCount: 2 },
  { id: 'cat-06', slug: 'bal', name: 'Bal', description: 'Çiçek, çam, kestane, meşe ve orman balı çeşitleri. %100 doğal ve katkısız.', image: '/images/products/bal.png', productCount: 11 },
  { id: 'cat-07', slug: 'bitkisel-yaglar', name: 'Bitkisel Yağlar', description: 'Geleneksel yöntemlerle hazırlanan saf bitkisel yağlar.', image: '/images/products/karisim.png', productCount: 1 },
];

export const ARIHAYAT_SITE_INFO = {
  name: 'Arı Hayat',
  tagline: '%100 Doğal Bal, Propolis ve Arı Ürünleri',
  description: 'Kendi arılıklarımızdan ürettiğimiz %100 doğal arı sütü, bal, propolis ve karışım ürünleri. Üreticiden tüketiciye doğrudan satış.',
  phone: '0536 341 19 84',
  whatsapp: '905353377251',
  whatsapp2: '905353377251',
  email: 'destek@arihayat.com',
  address: 'Bursa, Türkiye',
  instagram: 'https://www.instagram.com/arihayat',
  logoUrl: '/images/logo.png',
  announcementBar: '🐝 Ücretsiz Kargo: 1.500 TL ve Üzeri Alışverişlerde! Doğal ürünler, güvenilir teslimat.',
};
